config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :usa_product, -> { where(country_of_origin: "United States") }
  scope :most_reviewed, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

  before_save(:titleize_product)

  private
  def titleize_product
    self.name = self.name.titleize
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true, length: { minimum: 50, maximum: 250 }
  validates :rating, presence: true, numericality: { less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:admin, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:admin, :email, :password, :current_password)}

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    render :index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      flash[:alert] = "Product did not create, try again"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      flash[:alert] = "Product did not update, try again"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Review did not create, try again"
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to product_path(@review.product)
    else
      flash[:alert] = "Review did not update, try again"
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2 class='index-welcome'>Welcome to the Family!</h2>
<h4>Mario's Super Store is a one stop shop til you drop. You can find all your needs here... From Organic Candles to Jazz posters to the occasional Monster! Never shop anywhere else again!</h4>
<div class="row">
  <div class="col-sm-4 col-border">
    <h4 class="heading-border">Here is our most reviewed product:</h4>
    <% if @products.any? %>
    <ul>
      <% @products.most_reviewed.each do |p| %>
      <li><%= link_to p.name, product_path(p) %></li>
      <% end %>
    </ul>
    <% else %>
    <p>There are no products with the most reviews.</p>
    <% end %>
  </div>
  <div class="col-sm-4 col-border">
    <h4 class="heading-border">Here are products most recently added:</h4>
    <% if @products.any? %>
    <ul>
      <% @products.three_most_recent.each do |p| %>
      <li><%= link_to p.name, product_path(p) %></li>
      <% end %>
    </ul>
    <% else %>
    <p>There are no recent products.</p>
    <% end %>
  </div>
  <div class="col-sm-4 col-border">
    <h4 class="heading-border">Here are products made in the United States:</h4>
    <% if @products.any? %>
    <ul>
      <% @products.usa_product.each do |p| %>
      <li><%= link_to p.name, product_path(p) %></li>
      <% end %>
    </ul>
    <% else %>
    <p>There are no products made in the United States yet.</p>
    <% end %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cost %>
<%= f.number_field :cost, step: :any %>
<%= f.label :country_of_origin %>
<%= f.text_field :country_of_origin %>
<%= f.submit  %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mario Super Store</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "styles", media: "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <div class="main-nav">
      <p><%= link_to "Homepage", root_path %></p>
      <p id="products"><%= link_to "Products", products_path %></p>
      <% if current_user %>
      <p id="user-email"><%= current_user.email %></p>
      <p id="sign-out"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></p>
      <% else %>
      <p id="sign-up"><%= link_to "Sign Up", new_user_registration_path %></p>
      <p id="sign-in"><%= link_to "Sign In", new_user_session_path %></p>
      <% end %>
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div>
    <div class="jumbotron">
      <h1>Mario's Super Store</h1>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1 class='index-welcome'>Products</h1>
<div class="product-border">
<% if @products.any? %>
<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet.</p>
<% end %>

<% if current_user && current_user.admin %>
<p><%= link_to "Create new product", new_product_path %></p>
<% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><span class="underline">Product:</span> <%= @product.name %></h1>
<h2><span class="underline">Made in:</span> <%= @product.country_of_origin %></h2>
<h3><span class="underline">Price:</span> $<%= @product.cost %></h3>

<% if @product.reviews.any? %>
<h4 class="underline">Here are the reviews for this product:</h4>

<% @product.reviews.each do |review| %>
<ul>
  <li>
    <%= link_to review.author, product_review_path(@product, review) %>
  </li>
</ul>
<% end %>
<% else %>
<p>No reviews are listed for this product.</p>
<% end %>
<% if current_user %>
<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<% end %>
<% if current_user && current_user.admin %>
<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
  :data => {:confirm => "You sure?",
  :method => "delete"} %></p>
  <% end %>
  <p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Add a new review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Product: <%= @product.name %></h1>
<h2>Author: <%= @review.author %></h2>
<h3>Rating: <%= @review.rating %></h3>
<h4>Review: <%= @review.content_body.gsub(/\W/, " ") %></h4>
<% if current_user && current_user.admin %>
<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<% end %>
<p><%= link_to "Return to product", product_path(@product) %></p>